<a href="https://colab.research.google.com/github/virdel/Tensorflow-Practice-Code/blob/main/%E2%80%9CTensorflow%E5%9F%BA%E7%A1%80%E2%80%9D%E7%9A%84%E5%89%AF%E6%9C%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

tf.__version__

'2.3.0'

In [ ]:
#定义一个随机数
randon_float=tf.random.uniform(shape=())


zero_vector=tf.zeros(shape=(2))

A=tf.constant([[1.,2.],[3.,4.]])
B=tf.constant([[5.,6.],[7.,8.]])


print(A.shape)
print(B.dtype)
print(A.numpy)



(2, 2)
<dtype: 'float32'>
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>>


In [ ]:
C=tf.add(A,B)
D=tf.matmul(A,B)

print(C,D)



tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32) tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


# 自动求导机制

In [ ]:
x=tf.Variable(initial_value=3.)
with tf.GradientTape() as Tape:
  y=tf.square(x)

y_grad=Tape.gradient(y,x)

print(y_grad)

tf.Tensor(6.0, shape=(), dtype=float32)


In [ ]:
W=tf.Variable(initial_value=[[1.],[2.]])
B=tf.Variable(initial_value=1.)

x=tf.constant([[1.,2.],[3.,4.]])
y=tf.constant([[1.],[2.]])


with tf.GradientTape() as Tape:
  #L=(x*W+B-y)**2
  L=tf.reduce_sum(tf.square(tf.matmul(x,W)+B-y))

w_grad,b_grad=Tape.gradient(L,[W,B])

print(w_grad,b_grad)

tf.Tensor(
[[ 70.]
 [100.]], shape=(2, 1), dtype=float32) tf.Tensor(30.0, shape=(), dtype=float32)


#numpy线性回归

In [ ]:
import numpy as np

X_raw=np.array([2013,2014,2015,2016,2017],dtype=np.float32)
Y_raw=np.array([12000,14000,15000,16500,17500],dtype=np.float32)

X=(X_raw-X_raw.min())/(X_raw.max()-X_raw.min())
Y=(Y_raw-Y_raw.min())/(X_raw.max()-Y_raw.min())


In [ ]:
a,b=0,0
num_epoch=10000
learning_rate=1e-3

for e in range(num_epoch):
  y_pred=a*X+b
  grad_a,grad_b=2*(y_pred-Y).dot(X),2*(y_pred-Y).sum()
  a,b=a-learning_rate*grad_a,b-learning_rate*grad_b

print(a,b)

-0.5408971397206209 -0.030063514035195454


# tensorflow 线性回归

In [ ]:
x=tf.constant(X)
y=tf.constant(Y)
print(x,y)

tf.Tensor([0.   0.25 0.5  0.75 1.  ], shape=(5,), dtype=float32) tf.Tensor([-0.         -0.20034058 -0.30051088 -0.4507663  -0.5509366 ], shape=(5,), dtype=float32)


In [ ]:
a=tf.Variable(initial_value=0.)
b=tf.Variable(initial_value=0.)

variables=[a,b]

num_epoch=10000
optimizer=tf.keras.optimizers.SGD(learning_rate=1e-3)

for e in range(num_epoch):
  with tf.GradientTape() as Tape:
    y_pred=a*x+b
    loss=tf.reduce_sum(tf.square(y_pred-y))
  grads=Tape.gradient(loss,variables)

  optimizer.apply_gradients(grads_and_vars=zip(grads,variables))

print(a,b)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=-0.5408933> <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=-0.030064821>
